CREATE DATABASE IF NOT EXISTS DB_DATABASE;

CREATE USER IF NOT EXISTS DB_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_PASSWORD';

GRANT ALL PRIVILEGES ON DATABASE DB_DATABASE TO DB_USER;

CREATE USER IF NOT EXISTS DB_REPL_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_REPL_PASSWORD';

\c DB_DATABASE;

CREATE TABLE IF NOT EXISTS emails (
    ID SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS phones (
    id SERIAL PRIMARY KEY,
    phone VARCHAR(20) NOT NULL
);

INSERT INTO emails (email) VALUES ('example@test.com');

INSERT INTO phones (phone) VALUES ('+79269998877');